### ISSUE TITLE
最新的API案例和官方文档不一致

### ISSUE THREAD

**Issue by hidehalo** [FacePlusPlus/facepp-php-sdk#6]
//在demo中是这样写的
$params['img']          = '{image file path}';
//官方的最新的api是这样说的
通过POST方法上传的二进制数据，原始图片大小需要小于1M

**Comment by rickerd** [comment]
? English plz

**Comment by hidehalo** [comment]
the API doc about "/detection/detect" is inconsistency a few days ago,I checked it again currently,it's okay now
